### Transactions Index
GET http://localhost:3000/transactions.json

###Transactions Create
POST http://localhost:3000/transactions.json
Content-Type: application/json

{"transactions" :
  {
    "payer": "Dannon",
    "points": 1000,
    "timestamp": "2020-11-02T14:00:00Z"
  }
}
### Payers Index
GET http://localhost:3000/payers.json

### Transactions Show
GET http://localhost:3000/transactions/1.json


### Spend Points
POST http://localhost:3000/transactions/spend.json 
Content-Type: application/json

{
  "points": 5000
}